### ISSUE TITLE
Add location information to Ansible inventory for Infra, Prod and some of Test

### ISSUE THREAD

**Issue by larsks** [OCP-on-NERC/nerc-ansible#2]
We need to add location (pod/rack/elevation) to the Ansible inventory so that we can reference that in reports, when creating maintenance issues, etc.

This will require editing the `ocp-*.yaml` files in `inventory/00-static` to add additional variables to each host.

Given inventory content like this:

```
              hosts:
                wrk-0.nerc-ocp-prod.rc.fas.harvard.edu:
                wrk-1.nerc-ocp-prod.rc.fas.harvard.edu:
```

The modified version would look something like:

```
              hosts:
                wrk-0.nerc-ocp-prod.rc.fas.harvard.edu:
                  location:
                    row: 3
                    pod: B
                    cage: 1
                    unitnumber: 22
                wrk-1.nerc-ocp-prod.rc.fas.harvard.edu:
                  location:
                    row: 3
                    pod: B
                    cage: 1
                    unitnumber: 24
```

Here I'm using `elevation` to mean "location within the rack"; I'm not
wedded to this terminology so feel free to suggest alternatives.
