### ISSUE TITLE
Add unitnumber for Test Cluster

### ISSUE THREAD

**Issue by joachimweyl** [OCP-on-NERC/nerc-ansible#6]
We need to add unitnumber to the Ansible inventory so that we can reference that in reports, when creating maintenance issues, etc.

This will require editing `inventory/00-static/ocp-test.yaml` to add additional variables to each host.

The modified version would look something like (as it would have unit filled):

```
              hosts:
                ctl-0.nerc-ocp-test.rc.fas.harvard.edu:
                  location:
                    row: 7
                    pod: B
                    cage: 19
                    unit: 1
```
